server:
  servlet:
    encoding:
      force: 'true'
      charset: UTF-8
  port: '8300'
spring:
  application:
    name: sensor-data
  profiles:
    active: prod
springdoc:
  default-produces-media-type: application/json
  show-actuator: 'true'
  swagger-ui:
    disable-swagger-default-url: 'true'
    groups-order: desc
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: 'true'
  api-docs:
    path: /api-docs
  paths-to-match: /api/**
influxdb:
  bucket: TxT-iot
  token: noC68n9KNe6HJd20B9HFaRf68SuYV2lLVdGuuj1aFZb9xaJ4wlkL7Wxf02_ajEVxgw8PupjrTAwQo7kX6K65fA==
  url: http://133.186.217.132:8086
  org: TXT
